name: Mac App

on: [workflow_dispatch]

env:
  PYVER: "3.14"
  QT_API: "pyqt6"

jobs:
  macapp:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with: { python-version: "${{ env.PYVER }}" }
      - run: python --version
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade -e .[$QT_API,pygments,mfusepy]  # install dependencies (installing GF itself isn't necessary)
      - run: python -m pip install --upgrade pyinstaller
      - run: ./pkg/pyinstaller/build-macos-app.sh
      # upload-artifact has trouble with symlinks, use ditto to zip up the app
      - run: ditto -c -k --keepParent dist/GitFourchette.app GitFourchette-mac.zip
      - uses: actions/upload-artifact@v6
        with: { name: mac-app, path: GitFourchette-mac.zip, compression-level: 0 }
